# Netlify Configuration for AgentFlow
# This ensures React Router works correctly

[build]
  command = "npm run build"
  publish = "dist"

# Redirect all requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
